#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestKendoUI
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VAHamptonAcceliPlan")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCommonStudent(CommonStudent instance);
    partial void UpdateCommonStudent(CommonStudent instance);
    partial void DeleteCommonStudent(CommonStudent instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["VAHamptonAcceliPlanConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CommonStudent> CommonStudents
		{
			get
			{
				return this.GetTable<CommonStudent>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CommonStudent")]
	public partial class CommonStudent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CommonStudentId;
		
		private int _CommonSchoolId;
		
		private int _CommonStudentStatusId;
		
		private string _UniqueId;
		
		private System.Nullable<System.DateTime> _EnrollmentDate;
		
		private System.Nullable<System.DateTime> _InactiveDate;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _MiddleName;
		
		private string _Ssn;
		
		private System.DateTime _BirthDate;
		
		private string _LegalFirstName;
		
		private string _LegalLastName;
		
		private string _LegalMiddleName;
		
		private string _LegalSsn;
		
		private System.Nullable<System.DateTime> _LegalBirthDate;
		
		private int _SexType;
		
		private int _GradeType;
		
		private string _MedicaidNo;
		
		private string _ZipCode;
		
		private string _City;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _CreatedBy;
		
		private System.DateTime _CreatedDate;
		
		private string _UpdatedBy;
		
		private System.DateTime _UpdatedDate;
		
		private string _SuffixName;
		
		private System.Nullable<int> _RaceAutoId;
		
		private System.Nullable<System.DateTime> _InitialEvaluationDate;
		
		private System.Data.Linq.Binary _Avatar;
		
		private string _StateTestingIdentifier;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCommonStudentIdChanging(int value);
    partial void OnCommonStudentIdChanged();
    partial void OnCommonSchoolIdChanging(int value);
    partial void OnCommonSchoolIdChanged();
    partial void OnCommonStudentStatusIdChanging(int value);
    partial void OnCommonStudentStatusIdChanged();
    partial void OnUniqueIdChanging(string value);
    partial void OnUniqueIdChanged();
    partial void OnEnrollmentDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEnrollmentDateChanged();
    partial void OnInactiveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnInactiveDateChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnSsnChanging(string value);
    partial void OnSsnChanged();
    partial void OnBirthDateChanging(System.DateTime value);
    partial void OnBirthDateChanged();
    partial void OnLegalFirstNameChanging(string value);
    partial void OnLegalFirstNameChanged();
    partial void OnLegalLastNameChanging(string value);
    partial void OnLegalLastNameChanged();
    partial void OnLegalMiddleNameChanging(string value);
    partial void OnLegalMiddleNameChanged();
    partial void OnLegalSsnChanging(string value);
    partial void OnLegalSsnChanged();
    partial void OnLegalBirthDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLegalBirthDateChanged();
    partial void OnSexTypeChanging(int value);
    partial void OnSexTypeChanged();
    partial void OnGradeTypeChanging(int value);
    partial void OnGradeTypeChanged();
    partial void OnMedicaidNoChanging(string value);
    partial void OnMedicaidNoChanged();
    partial void OnZipCodeChanging(string value);
    partial void OnZipCodeChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnAddress1Changing(string value);
    partial void OnAddress1Changed();
    partial void OnAddress2Changing(string value);
    partial void OnAddress2Changed();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnCreatedDateChanging(System.DateTime value);
    partial void OnCreatedDateChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    partial void OnUpdatedDateChanging(System.DateTime value);
    partial void OnUpdatedDateChanged();
    partial void OnSuffixNameChanging(string value);
    partial void OnSuffixNameChanged();
    partial void OnRaceAutoIdChanging(System.Nullable<int> value);
    partial void OnRaceAutoIdChanged();
    partial void OnInitialEvaluationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnInitialEvaluationDateChanged();
    partial void OnAvatarChanging(System.Data.Linq.Binary value);
    partial void OnAvatarChanged();
    partial void OnStateTestingIdentifierChanging(string value);
    partial void OnStateTestingIdentifierChanged();
    #endregion
		
		public CommonStudent()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommonStudentId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CommonStudentId
		{
			get
			{
				return this._CommonStudentId;
			}
			set
			{
				if ((this._CommonStudentId != value))
				{
					this.OnCommonStudentIdChanging(value);
					this.SendPropertyChanging();
					this._CommonStudentId = value;
					this.SendPropertyChanged("CommonStudentId");
					this.OnCommonStudentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommonSchoolId", DbType="Int NOT NULL")]
		public int CommonSchoolId
		{
			get
			{
				return this._CommonSchoolId;
			}
			set
			{
				if ((this._CommonSchoolId != value))
				{
					this.OnCommonSchoolIdChanging(value);
					this.SendPropertyChanging();
					this._CommonSchoolId = value;
					this.SendPropertyChanged("CommonSchoolId");
					this.OnCommonSchoolIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommonStudentStatusId", DbType="Int NOT NULL")]
		public int CommonStudentStatusId
		{
			get
			{
				return this._CommonStudentStatusId;
			}
			set
			{
				if ((this._CommonStudentStatusId != value))
				{
					this.OnCommonStudentStatusIdChanging(value);
					this.SendPropertyChanging();
					this._CommonStudentStatusId = value;
					this.SendPropertyChanged("CommonStudentStatusId");
					this.OnCommonStudentStatusIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UniqueId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UniqueId
		{
			get
			{
				return this._UniqueId;
			}
			set
			{
				if ((this._UniqueId != value))
				{
					this.OnUniqueIdChanging(value);
					this.SendPropertyChanging();
					this._UniqueId = value;
					this.SendPropertyChanged("UniqueId");
					this.OnUniqueIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnrollmentDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EnrollmentDate
		{
			get
			{
				return this._EnrollmentDate;
			}
			set
			{
				if ((this._EnrollmentDate != value))
				{
					this.OnEnrollmentDateChanging(value);
					this.SendPropertyChanging();
					this._EnrollmentDate = value;
					this.SendPropertyChanged("EnrollmentDate");
					this.OnEnrollmentDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InactiveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> InactiveDate
		{
			get
			{
				return this._InactiveDate;
			}
			set
			{
				if ((this._InactiveDate != value))
				{
					this.OnInactiveDateChanging(value);
					this.SendPropertyChanging();
					this._InactiveDate = value;
					this.SendPropertyChanged("InactiveDate");
					this.OnInactiveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(50)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ssn", DbType="NVarChar(11)")]
		public string Ssn
		{
			get
			{
				return this._Ssn;
			}
			set
			{
				if ((this._Ssn != value))
				{
					this.OnSsnChanging(value);
					this.SendPropertyChanging();
					this._Ssn = value;
					this.SendPropertyChanged("Ssn");
					this.OnSsnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthDate", DbType="DateTime NOT NULL")]
		public System.DateTime BirthDate
		{
			get
			{
				return this._BirthDate;
			}
			set
			{
				if ((this._BirthDate != value))
				{
					this.OnBirthDateChanging(value);
					this.SendPropertyChanging();
					this._BirthDate = value;
					this.SendPropertyChanged("BirthDate");
					this.OnBirthDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegalFirstName", DbType="NVarChar(50)")]
		public string LegalFirstName
		{
			get
			{
				return this._LegalFirstName;
			}
			set
			{
				if ((this._LegalFirstName != value))
				{
					this.OnLegalFirstNameChanging(value);
					this.SendPropertyChanging();
					this._LegalFirstName = value;
					this.SendPropertyChanged("LegalFirstName");
					this.OnLegalFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegalLastName", DbType="NVarChar(50)")]
		public string LegalLastName
		{
			get
			{
				return this._LegalLastName;
			}
			set
			{
				if ((this._LegalLastName != value))
				{
					this.OnLegalLastNameChanging(value);
					this.SendPropertyChanging();
					this._LegalLastName = value;
					this.SendPropertyChanged("LegalLastName");
					this.OnLegalLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegalMiddleName", DbType="NVarChar(50)")]
		public string LegalMiddleName
		{
			get
			{
				return this._LegalMiddleName;
			}
			set
			{
				if ((this._LegalMiddleName != value))
				{
					this.OnLegalMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._LegalMiddleName = value;
					this.SendPropertyChanged("LegalMiddleName");
					this.OnLegalMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegalSsn", DbType="NVarChar(11)")]
		public string LegalSsn
		{
			get
			{
				return this._LegalSsn;
			}
			set
			{
				if ((this._LegalSsn != value))
				{
					this.OnLegalSsnChanging(value);
					this.SendPropertyChanging();
					this._LegalSsn = value;
					this.SendPropertyChanged("LegalSsn");
					this.OnLegalSsnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegalBirthDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LegalBirthDate
		{
			get
			{
				return this._LegalBirthDate;
			}
			set
			{
				if ((this._LegalBirthDate != value))
				{
					this.OnLegalBirthDateChanging(value);
					this.SendPropertyChanging();
					this._LegalBirthDate = value;
					this.SendPropertyChanged("LegalBirthDate");
					this.OnLegalBirthDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SexType", DbType="Int NOT NULL")]
		public int SexType
		{
			get
			{
				return this._SexType;
			}
			set
			{
				if ((this._SexType != value))
				{
					this.OnSexTypeChanging(value);
					this.SendPropertyChanging();
					this._SexType = value;
					this.SendPropertyChanged("SexType");
					this.OnSexTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeType", DbType="Int NOT NULL")]
		public int GradeType
		{
			get
			{
				return this._GradeType;
			}
			set
			{
				if ((this._GradeType != value))
				{
					this.OnGradeTypeChanging(value);
					this.SendPropertyChanging();
					this._GradeType = value;
					this.SendPropertyChanged("GradeType");
					this.OnGradeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicaidNo", DbType="NVarChar(14)")]
		public string MedicaidNo
		{
			get
			{
				return this._MedicaidNo;
			}
			set
			{
				if ((this._MedicaidNo != value))
				{
					this.OnMedicaidNoChanging(value);
					this.SendPropertyChanging();
					this._MedicaidNo = value;
					this.SendPropertyChanged("MedicaidNo");
					this.OnMedicaidNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode", DbType="NVarChar(10)")]
		public string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				if ((this._ZipCode != value))
				{
					this.OnZipCodeChanging(value);
					this.SendPropertyChanging();
					this._ZipCode = value;
					this.SendPropertyChanged("ZipCode");
					this.OnZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="NVarChar(50)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this.OnAddress1Changing(value);
					this.SendPropertyChanging();
					this._Address1 = value;
					this.SendPropertyChanged("Address1");
					this.OnAddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="NVarChar(50)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this.OnAddress2Changing(value);
					this.SendPropertyChanging();
					this._Address2 = value;
					this.SendPropertyChanged("Address2");
					this.OnAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedDate
		{
			get
			{
				return this._UpdatedDate;
			}
			set
			{
				if ((this._UpdatedDate != value))
				{
					this.OnUpdatedDateChanging(value);
					this.SendPropertyChanging();
					this._UpdatedDate = value;
					this.SendPropertyChanged("UpdatedDate");
					this.OnUpdatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuffixName", DbType="NVarChar(50)")]
		public string SuffixName
		{
			get
			{
				return this._SuffixName;
			}
			set
			{
				if ((this._SuffixName != value))
				{
					this.OnSuffixNameChanging(value);
					this.SendPropertyChanging();
					this._SuffixName = value;
					this.SendPropertyChanged("SuffixName");
					this.OnSuffixNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RaceAutoId", DbType="Int")]
		public System.Nullable<int> RaceAutoId
		{
			get
			{
				return this._RaceAutoId;
			}
			set
			{
				if ((this._RaceAutoId != value))
				{
					this.OnRaceAutoIdChanging(value);
					this.SendPropertyChanging();
					this._RaceAutoId = value;
					this.SendPropertyChanged("RaceAutoId");
					this.OnRaceAutoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InitialEvaluationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> InitialEvaluationDate
		{
			get
			{
				return this._InitialEvaluationDate;
			}
			set
			{
				if ((this._InitialEvaluationDate != value))
				{
					this.OnInitialEvaluationDateChanging(value);
					this.SendPropertyChanging();
					this._InitialEvaluationDate = value;
					this.SendPropertyChanged("InitialEvaluationDate");
					this.OnInitialEvaluationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avatar", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Avatar
		{
			get
			{
				return this._Avatar;
			}
			set
			{
				if ((this._Avatar != value))
				{
					this.OnAvatarChanging(value);
					this.SendPropertyChanging();
					this._Avatar = value;
					this.SendPropertyChanged("Avatar");
					this.OnAvatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateTestingIdentifier", DbType="NVarChar(50)")]
		public string StateTestingIdentifier
		{
			get
			{
				return this._StateTestingIdentifier;
			}
			set
			{
				if ((this._StateTestingIdentifier != value))
				{
					this.OnStateTestingIdentifierChanging(value);
					this.SendPropertyChanging();
					this._StateTestingIdentifier = value;
					this.SendPropertyChanged("StateTestingIdentifier");
					this.OnStateTestingIdentifierChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
